apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  labels:
    app: {{ .Values.labels }}
spec:
  ports:
    - port: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Values.labels }}