apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      labels:
        app: myapp-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14.2
        ports:
          - containerPort: 80
        volumeMounts:
        - name: configmap-volume
          mountPath: /usr/share/nginx/html
      - name: multitool-container
        image: wbitt/network-multitool
        ports: 
          - name: http-port
            containerPort: 1180
          - name: https-port
            containerPort: 11443
        env:
          - name: HTTP_PORT
            valueFrom: 
              configMapKeyRef:
                name: my-configmap-env
                key: multitool-container_port
          - name: HTTPS_PORT
            valueFrom: 
                configMapKeyRef:
                  name: my-configmap-env
                  key: multitool-container_port_ssl
      volumes:
      - name: configmap-volume
        configMap:
          name: configmap-nginx-page
        